### ISSUE TITLE
это сделать надо

### ISSUE THREAD

**Issue by stakenschneider** [stakenschneider/HexTetris#2]
добавь счетчик прокрутки песен, посмотрим сколько раз за все время эта сука сыграла
(счетчик открой с 2983749, потому что столько примерно раз мы ее уже прослушали)

**Comment by Lorismelik** [comment]
Что это за <Роскомнадзор>?

**Comment by stakenschneider** [comment]
люблю статистику, добавим на слайды и, вообще, что за вопросы?
Я - owner, ты какой-то contributor, так что пиши, а не спрашивай ╰(_´︶`_)╯
